blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostList.as_view(), name='post_list'),
    # path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('search/', views.search, name='search'),
    path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    # path('post/new/', views.post_new, name='post_new'),
    path('post/new/', views.PostCreate.as_view(), name='post_new'),
    # path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/edit/', views.PostUpdate.as_view(), name='post_edit'),
    # path('post/post/<int:pk>/delete', views.post_remove, name='post_remove'),
    path('post/post/<int:pk>/delete', views.PostDelete.as_view(), name='post_remove'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('post/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('post/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('post/signup', views.signup, name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

LOGIN_REDIRECT_URL = '/'

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout')
]

#dispaly images
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.shortcuts import reverse
from ckeditor.fields import RichTextField

# Create your models here.
def upload_location(instance, filename):
    return '%s/%s' %(instance.id, filename)

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = RichTextField(blank=True, null=True)
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True, height_field='height_field', width_field='width_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.pk])

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')#related_names allows us access within the Post model
    author = models.CharField(max_length=200)
    text = RichTextField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment =True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from blog.models import Post, Comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):
    """our post html form"""

    class Meta:
        model = Post
        fields = ('title', 'text','image' )

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text', )

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=50, required=True, help_text='Optional')
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=False)
    email = forms.EmailField(required=True, help_text='Please Input a valid email account')
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )
    
    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']


        if commit:
            user.save()

        return user

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from blog.models import Post, Comment
from django.utils import timezone
from blog.forms import PostForm , CommentForm, RegisterForm
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    ListView, DetailView, UpdateView, CreateView, DeleteView,
)
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

def post_list(request):
    """show post list"""
    template_name = 'blog/post_list.html'
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    context = {'posts': posts,}
    return render(request, template_name, context)

def post_detail(request, pk):
    """show detail"""
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, pk=pk)
    context = {'post':post}
    return render(request, template_name, context)

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)#save but do not commit to the database yet until user has been confirmed
            # print("before, ", post)
            post.author = request.user
            #post.published_date = timezone.now()
            # print("after, ", post)
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    template_name = 'blog/post_edit.html'
    context = {'form': form,}
    return render(request, template_name, context)

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            #post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    template_name = 'blog/post_edit.html'
    context = {'form':form}
    return render(request, template_name, context)

@login_required
def post_remove(request, pk):
    post = Post.objects.get(pk=pk).delete()
    return redirect('blog:post_list')

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('-created_date')
    template_name = 'blog/post_draft_list.html'
    context = {'posts':posts}
    return render(request, template_name, context)

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect(post.get_absolute_url())#redirects to the post_detail page defined as a fxn (get_absolue_url) in models.py 

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
        template_name = 'blog/add_comment_to_post.html'
        context = {'form':form}
    return render(request, template_name, context)

def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)
    
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)

# def signup(request):
#     if request.method == 'POST':
#         form = RegisterForm(request.POST)
#         if form.is_valid():
#             form.save()
#             # username = user.cleaned_data.get('username')
#             # raw_password = user.cleaned_data.get('password1')
#             # user = authenticate(username=username, password=raw_password)
#             # login(request, user)
#             return redirect('blog:post_list')
#     else:
#         form = RegisterForm()
#         context = {'form': form}
#         template_name = 'registration/signup.html'
#     return render(request, template_name, context)

def signup(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:post_list')
    else:
        form = RegisterForm()
        
        template_name = 'registration/signup.html'
        
        context = {'form': form}
    return render(request, template_name, context)


def search(request):
    template_name = 'blog/post_list.html'
    if request.method == 'GET':
        search_data = request.GET.get('q')
        # print(search_data)
        results = Post.objects.filter(title__icontains=search_data)
        context = {'posts': results, 'search':True}
        return render(request, template_name, context)
    else:
        # context = {'posts': None}
        return redirect("blog:post_list")





#CLASS BASED VIEW. in class based view all we need to specify is the model and the template.
class PostList(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'

class PostDetail(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post_edit.html'
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.published_date = timezone.now()
        # form.instance.image = form.cleaned_data['image']
        form.save()
        return super(PostCreate, self).form_valid(form)#super helps to take all of the properties of the form_valid fxn into the postcreate class

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/post_edit.html'
    form_class = PostForm

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog:post_list')

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-default" class="ml-2">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>HiiT Blog</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" rel="stylesheet">
        <link href=" {% static 'blog/css/blog.css' %}" rel="stylesheet">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class ="page-header">
            {% if request.user.is_authenticated %}
                <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <p class="top-menu">{{ request.user.username }}  <a href="{% url 'logout' %}" class="glyphicon glyphicon-log-out" onClick = "return confirm('Are you sure?');"></a></p>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
                <a href="{% url 'blog:signup' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <form action="{% url 'blog:search'%}" method="GET" style="margin-left:700px;">
                <input type="text" name="q" value="{{request.GET.q}}">
                <button type="submit">Search</button>
            </form>
            <h1><a href="/">Mini-Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}

{% block content%}
    <form method="post" onClick="return confirm('Are you sure?')">
        {% csrf_token %}
        <h2>Are you Sure you want to delete {{object.title}}?</h2>
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="post">
    {% if post.published_date %}
    <div class="date text-right">
        {{ post.published_date }}
    </div>
    {% else %}
        <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
    {% endif %}

    {% if request.user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil" class='mb-3'></span></a>
        <a href="{% url 'blog:post_remove' pk=post.pk %}" class="btn btn-danger" onClick = "return confirm('Are you sure?');"><span class="glyphicon glyphicon-remove"></span></a>
    {% endif %}
    <h2>{{ post.title|title }}</h2>

    {% if post.image %}
    <img src="{{ post.image.url }}" class = "img-responsive" style="height:100vh;">
    {% endif %}

    <h4><p>{{ post.text|safe }}</p></h4>
</div>

<a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>

{% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
    <div class="comment">
        <div class="date">
        {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
            {% endif %}
        </div>
        <h3><strong>{{ comment.author }}</strong></h3>
        <p>{{ comment.text|safe }}</p>
    </div>
    {% endif %}
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}

{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date text-right">
                <p>created: {{ post.created_date|date:'d-m-Y'}}</p>
            </div>
            <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title|title }}</a></h2>
            <p>{{ post.text|linebreaksbr|truncatechars:40 }}</p>
            <h3><a href="{% url 'blog:post_detail' pk=post.pk %}"</a>Read More</h3> 
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        <button class="btn btn-primary">Post</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% load static %}

{% block content %}

{% for post in posts %}
<div class="post">
    <div>
        {% if search %}
            <h3>Search Result for <span style="color:red;">{{request.GET.q}}</span></h3>
        {% endif %}
    </div>
    <div class="date text-right">
        <p>published: {{ post.published_date|timesince }} ago.</p>
    </div>
    <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title|title }}</a></h2>
    {% if post.image %}
    <img src="{{ post.image.url }}" class='img-responsive' style="height:100vh;">
    {% endif %}
    <h4><p>{{ post.text|safe|truncatechars:15 }}</p></h4>
    <h3><a href="{{post.get_absolute_url}}"</a>Read More</h3> 
    <a class='comments' href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
    <hr>
</div>
    {% empty %}
    <p>No Posts Found</p>
{% endfor %}
{% endblock %}